### ISSUE TITLE
Enable upsert of timeseries

### ISSUE THREAD

**Issue by linda-cognite** [cognitedata/cdp-spark-datasource#114]

**Comment by wjoel** [comment]
> Hmm, though it looks like their update resource endpoint uses name as primary index (not id), And they return `notFound: Array[String]`. https://doc.cognitedata.com/api/0.5/#operation/updateTimeSeries
> 
> So we can do this logic without having to change CDP (great 100 ), though it changes in 0.6 so it's good that the timeseries team is aware of our use case.
> 
> Process:
> 
>     1. Try updating timeseries by calling PUT->/api/0.5/projects/{project}/timeseries
> 
>     2. We're done if it responds with OK else if it's 404 go to step 3
> 
>     3. Read the notFound array and filter out the timeseries that are not found before calling PUT->/api/0.5/projects/{project}/timeseries again with this filter applied
> 
>     4. Then call POST->/api/0.5/projects/{project}/timeseries with timeseries that was not found during step 1.

From https://doc.cognitedata.com/api/0.6/#operation/alterTimeSeries it seems a `notFound` array will be returned also for 0.6, maybe this has changed (or I misunderstood you).

@hakontro will start looking into implementing this feature now.

**Comment by Tapped** [comment]
Maybe it works, though 0.6 doesn't have the PUT endpoint. Also I think 0.6 API of timeseries metadata is based on id and not name. So we can't do the 1. & 2. step, since we don't have the ID. The timeseries API need to introduce externalId, I'm surprised that they don't have it.

**Comment by linda-cognite** [comment]
So we will support referencing time series by name only, not by id?

**Comment by hakontro** [comment]
Closed by #174
