### ISSUE TITLE
Allow base URL to be configured

### ISSUE THREAD

**Issue by wjoel** [cognitedata/cdp-spark-datasource#151]
Now that we have "greenfield" as a staging environment it might be useful to change `https://api.cognitedata.com` to `https://greenfield.cognitedata.com`, so we should add a `CogniteBaseUrl` parameter to the common options.

The Python SDK uses `COGNITE_BASE_URL`, but we could also use `baseUrl` or `cdpBaseUrl`.

**Comment by hakontro** [comment]
#159
