### ISSUE TITLE
Add filter push down support for events

### ISSUE THREAD

**Issue by wjoel** [cognitedata/cdp-spark-datasource#172]
The [getEvents](https://doc.cognitedata.com/api/0.5/#operation/getEvents) API call has support for specifying values for a number of fields that we could use for predicate pushdown, similar to what we do for data points (using the time series name, and aggregates, and granularity).

Add support for `type` and `subtype`. Optionally add support for `minStartTime`, `maxStartTime`, `assetId` and `source` as well (if not, create a separate issue for those fields).

**Comment by hakontro** [comment]
Closed by #197
