### ISSUE TITLE
The write tutorial does not show actual writing

### ISSUE THREAD

**Issue by matiashf-cognite** [cognitedata/cdp-spark-datasource#209]
When I go through the Cognite Spark Datasource tutorials, the [write tutorial](https://westeurope.azuredatabricks.net/?o=2323107922886870#notebook/4149517249125246
) does not show examples of how to write.

Wishlist:
- `df.write.insertInto("some_temp_view")`
- `%sql insert ...`

**Comment by wjoel** [comment]
Yeah, that part isn't actually finished yet. It's near the top of our list of priorities, though!

**Comment by matiashf-cognite** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create types for time series in CDP](https://trello.com/c/XnvxS1DS/153-create-types-for-time-series-in-cdp)
