### ISSUE TITLE
Add support for partial updates

### ISSUE THREAD

**Issue by hakontro** [cognitedata/cdp-spark-datasource#214]
This would be more convenient and less error prone for users than having to provide the full DataFrame for updates.

**Comment by wjoel** [comment]
Would be a great feature.

This likely requires https://github.com/cognitedata/cdp-spark-datasource/issues/117 since Spark itself checks that source schema = destination schema on `.insertInto`, but it would be possible if we had `myDf.write.cdpEvents()`, `myDf.write.cdpDataPoints("tag-123")` etc.

**Comment by hakontro** [comment]
WIP #229

**Comment by hakontro** [comment]
#229
