### ISSUE TITLE
Low performance on selecting events by id

### ISSUE THREAD

**Issue by romanmotsar** [cognitedata/cdp-spark-datasource#235]
When you need to get some specific events by id's you can't do it fast enough. 
For comparison, `SELECT * FROM table` works fine

## Steps to reproduce:
1. Create table using cdp-spark-datasource
```
CREATE DATABASE IF NOT EXISTS cognite_data
DROP TABLE IF EXISTS cognite_data.api_events
CREATE TABLE IF NOT EXISTS cognite_data.api_events using com.cognite.spark.datasource
options (type 'events',
         apiKey '<COGNITE_API_KEY_PLACEHOLDER>',
         project '<PROJECT_PLACEHOLDER>')
```
2. Write an SQL query using IN statement
```
SELECT *
FROM cognite_data.api_events
WHERE id IN (<EVENT_ID_PLACEHOLDER>)
```

### Expected result
Get detailed information about this event in a few seconds

### Actual result
No data in 10 minutes

Also, I've tried `WHERE id=<SPECIFIC_EVENT_ID>` - same result

**Comment by hakontro** [comment]
Thanks for reporting. What number of events are in your tenant, and do you have a notebook I could look at? I wasn't able to reproduce - this worked fine for me when I ran your code against the events in 'publicdata'.

**Comment by wjoel** [comment]
This would be fixed by https://github.com/cognitedata/cdp-spark-datasource/issues/268

**Comment by hakontro** [comment]
https://github.com/cognitedata/cdp-spark-datasource/pull/276
