### ISSUE TITLE
Use v1 API to create timeseries with legacyName set

### ISSUE THREAD

**Issue by wjoel** [cognitedata/cdp-spark-datasource#285]
To ease the transition to v1 we should have a release that creates time series using the API v1 endpoint, but setting `legacyName` to equal `name`.

`legacyName` shouldn't be exposed to the end-user yet, but handled internally by us. That way we'll be creating time series that are visible in both v1 and 0.5/0.6.

**Comment by hakontro** [comment]
This is currently blocked by a bug in the timeseries api, but they're working on it.
https://trello.com/c/9VL1CDNA
