### ISSUE TITLE
Support for sequence resources Python

### ISSUE THREAD

**Issue by PhilippeBettler** [cognitedata/cdp-spark-datasource#429]
Hello,
Wanted to check if there is a plan to support sequence in Python.

**Comment by wjoel** [comment]
Hi! We plan to add support for sequences within the next couple of week. The Cognite Jira issue is CDF-5190, if you want to follow that.

**Comment by wchatx** [comment]
CDF-5190 is done and Sequences are [available](https://github.com/cognitedata/cdp-spark-datasource#sequences) in the Spark connector. Thanks!
