### ISSUE TITLE
Check if sanitation of db and table names is required for metric names

### ISSUE THREAD

**Issue by Tapped** [cognitedata/cdp-spark-datasource#64]
We create metrics like `UserMetricsSystem.counter(s"${metricsPrefix}raw.$database.$table.rows.created")`. If the metric names allow UTF-8 (or UTF-16?) we're fine, but if not, we may need to clean up the names if they allow arbitrary characters.

The names are also stored in our Postgres database, which uses UTF-8 encoding.

1) Find out if there are any restrictions on those names, and if they are sufficiently restrictive to be safe, consider this done.
2) If they are no sufficiently strict restrictions, check if UserMetricsSystem (which uses Dropwizard Metrics, aka. codahale metrics) allow metric names containing "funny" characters.
3) If funny characters are not allowed, decide how to sanitize the names. Easiest way might be to base64 encode the names and convert back somewhere else? Not ideal from a human readability point of view, though.

**Comment by wjoel** [comment]
@Tapped could you look into this?

**Comment by wjoel** [comment]
@Tapped ping?

**Comment by Tapped** [comment]
Yup I will 👍 I think it works though, haven't noticed any issues with æøå afaik
